apiVersion: apps/v1
kind: Deployment
metadata:
  name: tushar-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tushar-app
  template:
    metadata:
      labels:
        app: tushar-app
    spec:
      containers:
        - name: tushar-website
          image: tusharbhardwaj53/tushar-website:latest
          ports:
            - containerPort: 80
