services:
  website:
    image: tusharbhardwaj53/tushar-website:v2
    ports:
      - "8080:80"
    depends_on:
      - database

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: tushar
      POSTGRES_PASSWORD: devops123
    ports:
      - "5432:5432"
